# Generated by Django 5.1.1 on 2024-09-14 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_remove_appointment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 17, 34, 24, 439317, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='availability',
            name='appointment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 17, 34, 24, 439317, tzinfo=datetime.timezone.utc)),
        ),
    ]
