# Generated by Django 5.1.1 on 2024-09-14 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 18, 27, 53, 710948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='availability',
            name='appointment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 18, 27, 53, 710948, tzinfo=datetime.timezone.utc)),
        ),
    ]
