services:
  web:
    build: .
    container_name: django_medico
    command: >
      bash -c "until nc -z -v -w30 db 3306;
      do echo 'Waiting for MySQL...';
      sleep 2;
      done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=appbooking-f0dbbje8ewatbva5.canadacentral-01.azurewebsites.net,localhost,127.0.0.1
      - MYSQL_HOST=db
      - MYSQL_DATABASE=appoint
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - CSRF_TRUSTED_ORIGINS=https://appbooking-f0dbbje8ewatbva5.canadacentral-01.azurewebsites.net
    volumes:
      - .:/medico
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appoint
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s

volumes:
  mysql_data: {}